name: coffee_shop
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.6.0
  http: ^1.1.0
  injectable: ^2.2.0
  intl: ^0.19.0
  json_annotation: ^4.5.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  json_serializable: ^6.2.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
